### ISSUE TITLE
What about Android OS users?

### ISSUE THREAD

**Issue by fe01134** [ibm-watson-iot/iota-starter-server#1]
I own a Samsung S5 and wanted to try out this example and can't.  Feeling a bit left behind here.  I am sure I am not the only Android phone user.  Any plans to support Android with the sample app?

**Comment by mwakao** [comment]
We are working on Android client. The repository for it is https://github.ibm.com/Watson-IoT/IoT-Automotive-mobileApp-android

APK file is available for internal only. Please refer to the following link.
[https://apps.na.collabserv.com/forums/html/topic?id=ca1ec3e3-bd39-4b50-a505-569fbfafb4e1](https://apps.na.collabserv.com/forums/html/topic?id=ca1ec3e3-bd39-4b50-a505-569fbfafb4e1). 

We are going to make it public hopefully this week.
